version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Using Java 21"
      - java -version
      - mvn -version

  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
